# Generated by Django 4.0 on 2022-03-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souq', '0003_remove_product_description_product_oldprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aff_url',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
